### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by michael1900** [Eskander/ultra-popup-blocker#79]
Hi, last release is 9 months old. We will have a new release?

**Comment by Eskander** [comment]
Unlikely. This project is in maintenance so no new features are planned, but pull requests are welcome.
Are you missing a particular feature?

**Comment by yilmazdurmaz** [comment]
Hi @michael1900,
other than some edge cases we have in #27, I think the current version (however old) is doing well and capable to function possibly for a few more years, at least (or until browsers or monkeys(!) make breaking changes).
